// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.6.1
// source: voiceReader.proto

package voice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VoiceCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoiceCountRequest) Reset() {
	*x = VoiceCountRequest{}
	mi := &file_voiceReader_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoiceCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceCountRequest) ProtoMessage() {}

func (x *VoiceCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voiceReader_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceCountRequest.ProtoReflect.Descriptor instead.
func (*VoiceCountRequest) Descriptor() ([]byte, []int) {
	return file_voiceReader_proto_rawDescGZIP(), []int{0}
}

func (x *VoiceCountRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type VoiceCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoiceCountResponse) Reset() {
	*x = VoiceCountResponse{}
	mi := &file_voiceReader_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoiceCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceCountResponse) ProtoMessage() {}

func (x *VoiceCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voiceReader_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceCountResponse.ProtoReflect.Descriptor instead.
func (*VoiceCountResponse) Descriptor() ([]byte, []int) {
	return file_voiceReader_proto_rawDescGZIP(), []int{1}
}

func (x *VoiceCountResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VoiceCountResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *VoiceCountResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *VoiceCountResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type VoiceRetrieveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Index         int32                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoiceRetrieveRequest) Reset() {
	*x = VoiceRetrieveRequest{}
	mi := &file_voiceReader_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoiceRetrieveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceRetrieveRequest) ProtoMessage() {}

func (x *VoiceRetrieveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voiceReader_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceRetrieveRequest.ProtoReflect.Descriptor instead.
func (*VoiceRetrieveRequest) Descriptor() ([]byte, []int) {
	return file_voiceReader_proto_rawDescGZIP(), []int{2}
}

func (x *VoiceRetrieveRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VoiceRetrieveRequest) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type VoiceRetrieveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Chunk         []byte                 `protobuf:"bytes,2,opt,name=chunk,proto3" json:"chunk,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoiceRetrieveResponse) Reset() {
	*x = VoiceRetrieveResponse{}
	mi := &file_voiceReader_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoiceRetrieveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceRetrieveResponse) ProtoMessage() {}

func (x *VoiceRetrieveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voiceReader_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceRetrieveResponse.ProtoReflect.Descriptor instead.
func (*VoiceRetrieveResponse) Descriptor() ([]byte, []int) {
	return file_voiceReader_proto_rawDescGZIP(), []int{3}
}

func (x *VoiceRetrieveResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VoiceRetrieveResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *VoiceRetrieveResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *VoiceRetrieveResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_voiceReader_proto protoreflect.FileDescriptor

var file_voiceReader_proto_rawDesc = string([]byte{
	0x0a, 0x11, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x52, 0x65, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x23, 0x0a, 0x11, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x68, 0x0a, 0x12, 0x56, 0x6f, 0x69, 0x63,
	0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x22, 0x3c, 0x0a, 0x14, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x52, 0x65, 0x74, 0x72, 0x69,
	0x65, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x22, 0x6b, 0x0a, 0x15, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x75,
	0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x32, 0x7a, 0x0a,
	0x0b, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x52, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x30, 0x0a, 0x05,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x2e, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x56, 0x6f, 0x69, 0x63,
	0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39,
	0x0a, 0x08, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x12, 0x15, 0x2e, 0x56, 0x6f, 0x69,
	0x63, 0x65, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x76,
	0x6f, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_voiceReader_proto_rawDescOnce sync.Once
	file_voiceReader_proto_rawDescData []byte
)

func file_voiceReader_proto_rawDescGZIP() []byte {
	file_voiceReader_proto_rawDescOnce.Do(func() {
		file_voiceReader_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_voiceReader_proto_rawDesc), len(file_voiceReader_proto_rawDesc)))
	})
	return file_voiceReader_proto_rawDescData
}

var file_voiceReader_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_voiceReader_proto_goTypes = []any{
	(*VoiceCountRequest)(nil),     // 0: VoiceCountRequest
	(*VoiceCountResponse)(nil),    // 1: VoiceCountResponse
	(*VoiceRetrieveRequest)(nil),  // 2: VoiceRetrieveRequest
	(*VoiceRetrieveResponse)(nil), // 3: VoiceRetrieveResponse
}
var file_voiceReader_proto_depIdxs = []int32{
	0, // 0: VoiceReader.Count:input_type -> VoiceCountRequest
	2, // 1: VoiceReader.Retrieve:input_type -> VoiceRetrieveRequest
	1, // 2: VoiceReader.Count:output_type -> VoiceCountResponse
	3, // 3: VoiceReader.Retrieve:output_type -> VoiceRetrieveResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_voiceReader_proto_init() }
func file_voiceReader_proto_init() {
	if File_voiceReader_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_voiceReader_proto_rawDesc), len(file_voiceReader_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_voiceReader_proto_goTypes,
		DependencyIndexes: file_voiceReader_proto_depIdxs,
		MessageInfos:      file_voiceReader_proto_msgTypes,
	}.Build()
	File_voiceReader_proto = out.File
	file_voiceReader_proto_goTypes = nil
	file_voiceReader_proto_depIdxs = nil
}
