// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.6.1
// source: voiceWriter.proto

package voice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VoiceWriter_Submit_FullMethodName = "/VoiceWriter/Submit"
)

// VoiceWriterClient is the client API for VoiceWriter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VoiceWriterClient interface {
	Submit(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[VoiceSubmitRequest, VoiceSubmitResponse], error)
}

type voiceWriterClient struct {
	cc grpc.ClientConnInterface
}

func NewVoiceWriterClient(cc grpc.ClientConnInterface) VoiceWriterClient {
	return &voiceWriterClient{cc}
}

func (c *voiceWriterClient) Submit(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[VoiceSubmitRequest, VoiceSubmitResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VoiceWriter_ServiceDesc.Streams[0], VoiceWriter_Submit_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[VoiceSubmitRequest, VoiceSubmitResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VoiceWriter_SubmitClient = grpc.ClientStreamingClient[VoiceSubmitRequest, VoiceSubmitResponse]

// VoiceWriterServer is the server API for VoiceWriter service.
// All implementations must embed UnimplementedVoiceWriterServer
// for forward compatibility.
type VoiceWriterServer interface {
	Submit(grpc.ClientStreamingServer[VoiceSubmitRequest, VoiceSubmitResponse]) error
	mustEmbedUnimplementedVoiceWriterServer()
}

// UnimplementedVoiceWriterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVoiceWriterServer struct{}

func (UnimplementedVoiceWriterServer) Submit(grpc.ClientStreamingServer[VoiceSubmitRequest, VoiceSubmitResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Submit not implemented")
}
func (UnimplementedVoiceWriterServer) mustEmbedUnimplementedVoiceWriterServer() {}
func (UnimplementedVoiceWriterServer) testEmbeddedByValue()                     {}

// UnsafeVoiceWriterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VoiceWriterServer will
// result in compilation errors.
type UnsafeVoiceWriterServer interface {
	mustEmbedUnimplementedVoiceWriterServer()
}

func RegisterVoiceWriterServer(s grpc.ServiceRegistrar, srv VoiceWriterServer) {
	// If the following call pancis, it indicates UnimplementedVoiceWriterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VoiceWriter_ServiceDesc, srv)
}

func _VoiceWriter_Submit_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VoiceWriterServer).Submit(&grpc.GenericServerStream[VoiceSubmitRequest, VoiceSubmitResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VoiceWriter_SubmitServer = grpc.ClientStreamingServer[VoiceSubmitRequest, VoiceSubmitResponse]

// VoiceWriter_ServiceDesc is the grpc.ServiceDesc for VoiceWriter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VoiceWriter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "VoiceWriter",
	HandlerType: (*VoiceWriterServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Submit",
			Handler:       _VoiceWriter_Submit_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "voiceWriter.proto",
}
