// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.6.1
// source: voiceReader.proto

package voice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VoiceReader_Count_FullMethodName    = "/VoiceReader/Count"
	VoiceReader_Retrieve_FullMethodName = "/VoiceReader/Retrieve"
)

// VoiceReaderClient is the client API for VoiceReader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VoiceReaderClient interface {
	Count(ctx context.Context, in *VoiceCountRequest, opts ...grpc.CallOption) (*VoiceCountResponse, error)
	Retrieve(ctx context.Context, in *VoiceRetrieveRequest, opts ...grpc.CallOption) (*VoiceRetrieveResponse, error)
}

type voiceReaderClient struct {
	cc grpc.ClientConnInterface
}

func NewVoiceReaderClient(cc grpc.ClientConnInterface) VoiceReaderClient {
	return &voiceReaderClient{cc}
}

func (c *voiceReaderClient) Count(ctx context.Context, in *VoiceCountRequest, opts ...grpc.CallOption) (*VoiceCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VoiceCountResponse)
	err := c.cc.Invoke(ctx, VoiceReader_Count_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceReaderClient) Retrieve(ctx context.Context, in *VoiceRetrieveRequest, opts ...grpc.CallOption) (*VoiceRetrieveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VoiceRetrieveResponse)
	err := c.cc.Invoke(ctx, VoiceReader_Retrieve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VoiceReaderServer is the server API for VoiceReader service.
// All implementations must embed UnimplementedVoiceReaderServer
// for forward compatibility.
type VoiceReaderServer interface {
	Count(context.Context, *VoiceCountRequest) (*VoiceCountResponse, error)
	Retrieve(context.Context, *VoiceRetrieveRequest) (*VoiceRetrieveResponse, error)
	mustEmbedUnimplementedVoiceReaderServer()
}

// UnimplementedVoiceReaderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVoiceReaderServer struct{}

func (UnimplementedVoiceReaderServer) Count(context.Context, *VoiceCountRequest) (*VoiceCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Count not implemented")
}
func (UnimplementedVoiceReaderServer) Retrieve(context.Context, *VoiceRetrieveRequest) (*VoiceRetrieveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Retrieve not implemented")
}
func (UnimplementedVoiceReaderServer) mustEmbedUnimplementedVoiceReaderServer() {}
func (UnimplementedVoiceReaderServer) testEmbeddedByValue()                     {}

// UnsafeVoiceReaderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VoiceReaderServer will
// result in compilation errors.
type UnsafeVoiceReaderServer interface {
	mustEmbedUnimplementedVoiceReaderServer()
}

func RegisterVoiceReaderServer(s grpc.ServiceRegistrar, srv VoiceReaderServer) {
	// If the following call pancis, it indicates UnimplementedVoiceReaderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VoiceReader_ServiceDesc, srv)
}

func _VoiceReader_Count_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoiceCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceReaderServer).Count(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceReader_Count_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceReaderServer).Count(ctx, req.(*VoiceCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoiceReader_Retrieve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoiceRetrieveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceReaderServer).Retrieve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceReader_Retrieve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceReaderServer).Retrieve(ctx, req.(*VoiceRetrieveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VoiceReader_ServiceDesc is the grpc.ServiceDesc for VoiceReader service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VoiceReader_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "VoiceReader",
	HandlerType: (*VoiceReaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Count",
			Handler:    _VoiceReader_Count_Handler,
		},
		{
			MethodName: "Retrieve",
			Handler:    _VoiceReader_Retrieve_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "voiceReader.proto",
}
