// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.6.1
// source: voiceWriter.proto

package voice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VoiceSubmitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=jobId,proto3" json:"jobId,omitempty"`
	Audio         []byte                 `protobuf:"bytes,2,opt,name=audio,proto3" json:"audio,omitempty"` // The prompt content that will be processed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoiceSubmitRequest) Reset() {
	*x = VoiceSubmitRequest{}
	mi := &file_voiceWriter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoiceSubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceSubmitRequest) ProtoMessage() {}

func (x *VoiceSubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voiceWriter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceSubmitRequest.ProtoReflect.Descriptor instead.
func (*VoiceSubmitRequest) Descriptor() ([]byte, []int) {
	return file_voiceWriter_proto_rawDescGZIP(), []int{0}
}

func (x *VoiceSubmitRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *VoiceSubmitRequest) GetAudio() []byte {
	if x != nil {
		return x.Audio
	}
	return nil
}

type VoiceSubmitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoiceSubmitResponse) Reset() {
	*x = VoiceSubmitResponse{}
	mi := &file_voiceWriter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoiceSubmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceSubmitResponse) ProtoMessage() {}

func (x *VoiceSubmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voiceWriter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceSubmitResponse.ProtoReflect.Descriptor instead.
func (*VoiceSubmitResponse) Descriptor() ([]byte, []int) {
	return file_voiceWriter_proto_rawDescGZIP(), []int{1}
}

func (x *VoiceSubmitResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VoiceSubmitResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *VoiceSubmitResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_voiceWriter_proto protoreflect.FileDescriptor

var file_voiceWriter_proto_rawDesc = string([]byte{
	0x0a, 0x11, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x57, 0x72, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x40, 0x0a, 0x12, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x53, 0x75, 0x62, 0x6d,
	0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6a, 0x6f, 0x62,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x61, 0x75, 0x64, 0x69, 0x6f, 0x22, 0x53, 0x0a, 0x13, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x53, 0x75,
	0x62, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x32, 0x42, 0x0a, 0x0b, 0x56, 0x6f,
	0x69, 0x63, 0x65, 0x57, 0x72, 0x69, 0x74, 0x65, 0x72, 0x12, 0x33, 0x0a, 0x06, 0x53, 0x75, 0x62,
	0x6d, 0x69, 0x74, 0x12, 0x13, 0x2e, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x53, 0x75, 0x62, 0x6d, 0x69,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x56, 0x6f, 0x69, 0x63, 0x65,
	0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09,
	0x5a, 0x07, 0x2e, 0x3b, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
})

var (
	file_voiceWriter_proto_rawDescOnce sync.Once
	file_voiceWriter_proto_rawDescData []byte
)

func file_voiceWriter_proto_rawDescGZIP() []byte {
	file_voiceWriter_proto_rawDescOnce.Do(func() {
		file_voiceWriter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_voiceWriter_proto_rawDesc), len(file_voiceWriter_proto_rawDesc)))
	})
	return file_voiceWriter_proto_rawDescData
}

var file_voiceWriter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_voiceWriter_proto_goTypes = []any{
	(*VoiceSubmitRequest)(nil),  // 0: VoiceSubmitRequest
	(*VoiceSubmitResponse)(nil), // 1: VoiceSubmitResponse
}
var file_voiceWriter_proto_depIdxs = []int32{
	0, // 0: VoiceWriter.Submit:input_type -> VoiceSubmitRequest
	1, // 1: VoiceWriter.Submit:output_type -> VoiceSubmitResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_voiceWriter_proto_init() }
func file_voiceWriter_proto_init() {
	if File_voiceWriter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_voiceWriter_proto_rawDesc), len(file_voiceWriter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_voiceWriter_proto_goTypes,
		DependencyIndexes: file_voiceWriter_proto_depIdxs,
		MessageInfos:      file_voiceWriter_proto_msgTypes,
	}.Build()
	File_voiceWriter_proto = out.File
	file_voiceWriter_proto_goTypes = nil
	file_voiceWriter_proto_depIdxs = nil
}
