// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.6.1
// source: textReader.proto

package text

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TextCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextCountRequest) Reset() {
	*x = TextCountRequest{}
	mi := &file_textReader_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextCountRequest) ProtoMessage() {}

func (x *TextCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_textReader_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextCountRequest.ProtoReflect.Descriptor instead.
func (*TextCountRequest) Descriptor() ([]byte, []int) {
	return file_textReader_proto_rawDescGZIP(), []int{0}
}

func (x *TextCountRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TextCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextCountResponse) Reset() {
	*x = TextCountResponse{}
	mi := &file_textReader_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextCountResponse) ProtoMessage() {}

func (x *TextCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_textReader_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextCountResponse.ProtoReflect.Descriptor instead.
func (*TextCountResponse) Descriptor() ([]byte, []int) {
	return file_textReader_proto_rawDescGZIP(), []int{1}
}

func (x *TextCountResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type TextRetrieveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Index         int32                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextRetrieveRequest) Reset() {
	*x = TextRetrieveRequest{}
	mi := &file_textReader_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextRetrieveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextRetrieveRequest) ProtoMessage() {}

func (x *TextRetrieveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_textReader_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextRetrieveRequest.ProtoReflect.Descriptor instead.
func (*TextRetrieveRequest) Descriptor() ([]byte, []int) {
	return file_textReader_proto_rawDescGZIP(), []int{2}
}

func (x *TextRetrieveRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TextRetrieveRequest) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type TextRetrieveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Start         float64                `protobuf:"fixed64,3,opt,name=start,proto3" json:"start,omitempty"`
	End           float64                `protobuf:"fixed64,4,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextRetrieveResponse) Reset() {
	*x = TextRetrieveResponse{}
	mi := &file_textReader_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextRetrieveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextRetrieveResponse) ProtoMessage() {}

func (x *TextRetrieveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_textReader_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextRetrieveResponse.ProtoReflect.Descriptor instead.
func (*TextRetrieveResponse) Descriptor() ([]byte, []int) {
	return file_textReader_proto_rawDescGZIP(), []int{3}
}

func (x *TextRetrieveResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TextRetrieveResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TextRetrieveResponse) GetStart() float64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *TextRetrieveResponse) GetEnd() float64 {
	if x != nil {
		return x.End
	}
	return 0
}

var File_textReader_proto protoreflect.FileDescriptor

var file_textReader_proto_rawDesc = string([]byte{
	0x0a, 0x10, 0x74, 0x65, 0x78, 0x74, 0x52, 0x65, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x22, 0x0a, 0x10, 0x54, 0x65, 0x78, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x29, 0x0a, 0x11, 0x54, 0x65, 0x78, 0x74, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x22, 0x3b, 0x0a, 0x13, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x68,
	0x0a, 0x14, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x32, 0x75, 0x0a, 0x0a, 0x54, 0x65, 0x78, 0x74,
	0x52, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x2e, 0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x11, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x12, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x08, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65,
	0x76, 0x65, 0x12, 0x14, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x52,
	0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x08, 0x5a, 0x06, 0x2e, 0x3b, 0x74, 0x65, 0x78, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
})

var (
	file_textReader_proto_rawDescOnce sync.Once
	file_textReader_proto_rawDescData []byte
)

func file_textReader_proto_rawDescGZIP() []byte {
	file_textReader_proto_rawDescOnce.Do(func() {
		file_textReader_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_textReader_proto_rawDesc), len(file_textReader_proto_rawDesc)))
	})
	return file_textReader_proto_rawDescData
}

var file_textReader_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_textReader_proto_goTypes = []any{
	(*TextCountRequest)(nil),     // 0: TextCountRequest
	(*TextCountResponse)(nil),    // 1: TextCountResponse
	(*TextRetrieveRequest)(nil),  // 2: TextRetrieveRequest
	(*TextRetrieveResponse)(nil), // 3: TextRetrieveResponse
}
var file_textReader_proto_depIdxs = []int32{
	0, // 0: TextReader.Count:input_type -> TextCountRequest
	2, // 1: TextReader.Retrieve:input_type -> TextRetrieveRequest
	1, // 2: TextReader.Count:output_type -> TextCountResponse
	3, // 3: TextReader.Retrieve:output_type -> TextRetrieveResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_textReader_proto_init() }
func file_textReader_proto_init() {
	if File_textReader_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_textReader_proto_rawDesc), len(file_textReader_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_textReader_proto_goTypes,
		DependencyIndexes: file_textReader_proto_depIdxs,
		MessageInfos:      file_textReader_proto_msgTypes,
	}.Build()
	File_textReader_proto = out.File
	file_textReader_proto_goTypes = nil
	file_textReader_proto_depIdxs = nil
}
