// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.6.1
// source: textReader.proto

package text

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TextReader_Count_FullMethodName    = "/TextReader/Count"
	TextReader_Retrieve_FullMethodName = "/TextReader/Retrieve"
)

// TextReaderClient is the client API for TextReader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TextReaderClient interface {
	Count(ctx context.Context, in *TextCountRequest, opts ...grpc.CallOption) (*TextCountResponse, error)
	Retrieve(ctx context.Context, in *TextRetrieveRequest, opts ...grpc.CallOption) (*TextRetrieveResponse, error)
}

type textReaderClient struct {
	cc grpc.ClientConnInterface
}

func NewTextReaderClient(cc grpc.ClientConnInterface) TextReaderClient {
	return &textReaderClient{cc}
}

func (c *textReaderClient) Count(ctx context.Context, in *TextCountRequest, opts ...grpc.CallOption) (*TextCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TextCountResponse)
	err := c.cc.Invoke(ctx, TextReader_Count_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *textReaderClient) Retrieve(ctx context.Context, in *TextRetrieveRequest, opts ...grpc.CallOption) (*TextRetrieveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TextRetrieveResponse)
	err := c.cc.Invoke(ctx, TextReader_Retrieve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TextReaderServer is the server API for TextReader service.
// All implementations must embed UnimplementedTextReaderServer
// for forward compatibility.
type TextReaderServer interface {
	Count(context.Context, *TextCountRequest) (*TextCountResponse, error)
	Retrieve(context.Context, *TextRetrieveRequest) (*TextRetrieveResponse, error)
	mustEmbedUnimplementedTextReaderServer()
}

// UnimplementedTextReaderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTextReaderServer struct{}

func (UnimplementedTextReaderServer) Count(context.Context, *TextCountRequest) (*TextCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Count not implemented")
}
func (UnimplementedTextReaderServer) Retrieve(context.Context, *TextRetrieveRequest) (*TextRetrieveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Retrieve not implemented")
}
func (UnimplementedTextReaderServer) mustEmbedUnimplementedTextReaderServer() {}
func (UnimplementedTextReaderServer) testEmbeddedByValue()                    {}

// UnsafeTextReaderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TextReaderServer will
// result in compilation errors.
type UnsafeTextReaderServer interface {
	mustEmbedUnimplementedTextReaderServer()
}

func RegisterTextReaderServer(s grpc.ServiceRegistrar, srv TextReaderServer) {
	// If the following call pancis, it indicates UnimplementedTextReaderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TextReader_ServiceDesc, srv)
}

func _TextReader_Count_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TextReaderServer).Count(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TextReader_Count_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TextReaderServer).Count(ctx, req.(*TextCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TextReader_Retrieve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextRetrieveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TextReaderServer).Retrieve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TextReader_Retrieve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TextReaderServer).Retrieve(ctx, req.(*TextRetrieveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TextReader_ServiceDesc is the grpc.ServiceDesc for TextReader service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TextReader_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TextReader",
	HandlerType: (*TextReaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Count",
			Handler:    _TextReader_Count_Handler,
		},
		{
			MethodName: "Retrieve",
			Handler:    _TextReader_Retrieve_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "textReader.proto",
}
